 # espeleo locomotion parameters
 espeleo_locomotion: 

  # default locomotion type
  # 1 - 6 wheels mode
  # 2 - 6 legs mode
  locomotion_mode: 1

  # control update rate [Hz]
  control_rate: 10

  # Max axis joints speed [rad/s]
  joints_maxJointsSpeed: 3.1415

  # EspeleoRobo's max translational and rotational speeds 
  espeleo_maxTranslationalSpeed: 10   #[m/s]
  espeleo_maxRotationalSpeed: 10      #[rad/s]

  # wheels radius [m]
  wheeled_radius: 0.14   

  # wheeled mode kinematic parameters 
  wheeled_kinematic_lambda: 0.965
  wheeled_kinematic_ycir: 0.531

  # minimum phi slow angle for legged mode [rad]
  legged_phis_min: 0.1745

  # maximum phi slow angle for legged mode [rad]
  legged_phis_max: 0.7854
